//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int ID { get; set; }
        public Nullable<int> ID_Book { get; set; }
        public string Row { get; set; }
        public string oldvalue { get; set; }
        public string newvalue { get; set; }
        public Nullable<System.DateTime> ModificationTime { get; set; }
    }
}
