//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_First
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PublishingHouseEntities : DbContext
    {
        public PublishingHouseEntities()
            : base("name=PublishingHouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Themes> Themes { get; set; }
        public virtual DbSet<Audit> Audit { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<DeletedBooks> DeletedBooks { get; set; }
        public virtual DbSet<ShopAuthors> ShopAuthors { get; set; }
        public virtual DbSet<TempXMLBook> TempXMLBook { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Shops> Shops { get; set; }
    }
}
