//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int ID_Sale { get; set; }
        public Nullable<int> ID_Book { get; set; }
        public Nullable<System.DateTime> DateOfSale { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ID_Shop { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Shops Shops { get; set; }
    }
}
